
title: Services utilisables par linKut
desc:
  présnte quelques services de base utilisable avec l'application de redirection

#le champs data est passé au service de redirection avec un éventuel traitement préalable


services:
  - service: Redirection
    id: redirect
    data:
      domain: ''
    description: Redirection simple

  - service: Preuve d'humanitee
    id: poh
    data:
      domain: https://gate.nfluent.io/transfer
      message: Pour continuez, veuillez cliquer
    description: Vérifie que l'internaute n'est pas un robot

  - service: Authentification par wallet
    id: authent
    data:
      network: elrond-devnet
      connexion:
        address: False
        keystore: False
        wallet_connect: True
        email: False
        google: False
        extension_wallet: True
        web_wallet: True
        private_key: False
        direct_connect: True
        nfluent_wallet_connect: False
      domain: https://gate.nfluent.io/transfer
      message: Pour continuez, veuillez connecter votre wallet
    description: Identification du wallet MvX


  - service: Landing page
    id: landing_page
    data:
      domain: https://gate.nfluent.io/transfer
      background: "black"
      quantity: 1
    description: Permet d'afficher une écran, une image, une couleur pendant {{quantity}} secondes avant la redirection


  - service: Facturer des eGld
    id: TokenGate
    data:
      domain: https://gate.nfluent.io/transfer
      message: Pour continuez, veuillez régler {{quantity}} {{token}}
      token: egld
      connexion:
        address: False
        keystore: False
        wallet_connect: True
        email: False
        google: False
        extension_wallet: True
        web_wallet: True
        private_key: False
        direct_connect: True
        nfluent_wallet_connect: False
      network: elrond-devnet
      quantity: 0.01
      address: "?"
    description: L'utilisateur doit payer {{quantity}} {{token}} sur le {{network}} pour accéder au lien {{url}}


