title: Services utilisables par linKut
desc: ""

services:
  - service: Redirection
    id: redirect
    data:
      domain: ""
    description: Redirection simple

  - service: Preuve d'humanité
    id: POH
    data:
      humanity: True
      domain: https://api.f80.fr/transfer
    description: Redirection simple

  - service: Authentification par wallet
    id: authent
    data:
      authent: True
      domain: https://api.f80.fr/transfer
    description: Redirection simple

